### ISSUE TITLE
HTTP link to chrome.com

### ISSUE THREAD

**Issue by c20ms1** [PlanHubMe/NotSupported#1]
# What It Is

On line 39 of index.html, it says:
`<h3>To get to PlanHub, try upgrading your browser. We suggest Google Chrome, which can be downloaded <a href="http://chrome.com">here</a>.
</h3>`
# What it Should Be

`<h3>To get to PlanHub, try upgrading your browser. We suggest Google Chrome, which can be downloaded <a href="https://www.chrome.com">here</a>.</h3>`
# Why

You should always include https wherever possible for secure connections. I have no other real issues otherwise. I've even changed it in my own fork of your project.

**Comment by thatoddmailbox** [comment]
@c20ms1 Merged! Thanks for the help!
